name: CI

on:
  pull_request:
    branches:
      - devel
jobs:
    job1:
        name: Build
        runs-on: ubuntu-22.04
        container: ros:humble
        steps:
            - uses: actions/checkout@v2-beta
            - name: Copy repository
              run: |
                  mkdir -p ~/ros2_ws/src/kalman_filter_localization
                  cp -rf . ~/ros2_ws/src/kalman_filter_localization
            - name: Install dependencies
              run: |
                  source /opt/ros/humble/setup.bash
                  cd ~/ros2_ws/src
                  rosdep install -r -y --from-paths . --ignore-src
              shell: bash
            - name: Build packages
              run: |
                  source /opt/ros/humble/setup.bash
                  apt install python3-colcon-common-extensions
                  cd ~/ros2_ws
                  colcon build
                  source ~/ros2_ws/install/setup.bash
              shell: bash
